### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
timeout: 30
default_entry: 2
interface_branding: Omarchy Bootloader
# interface_branding_color: 2
hash_mismatch_panic: no

graphics: yes
auto_resolution: yes
wallpaper: boot():/frank1.png
wallpaper_style: stretched
backdrop: 000000

# Terminal colors (Tokyo Night palette)
# term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;a9b1d6
# term_palette_bright: 414868;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;c0caf5

term_palette: 15161e;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;ffffff
term_palette_bright: 414868;f7768e;9ece6a;e0af68;7aa2f7;bb9af7;7dcfff;ffffff

# Text colors
# text colors — muted white
term_foreground: f3eee8
term_foreground_bright: f3eee8

# cursor + title highlight — warm brown
interface_branding_color: 9ece6a
term_background_bright: 24283b

/EFI fallback
comment: Default EFI loader
comment: order-priority=10
protocol: efi
path: boot():/EFI/BOOT/BOOTX64.EFI
