"$schema" = 'https://starship.rs/config-schema.json'

palette = 'void'

format = """
[](fg:red)\
$os\
$username\
[](bg:magenta fg:red)\
$directory\
[](bg:yellow fg:magenta)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:cyan)\
$conda\
[](fg:cyan bg:blue)\
$time\
[ ](fg:blue)\
$cmd_duration\
$line_break\
$character"""

# -----------------------
# OS SEGMENT
# -----------------------
[os]
disabled = false
style = "bg:red fg:black"

[os.symbols]
Arch = "󰣇"
Linux = "󰌽"
Ubuntu = "󰕈"
Macos = "󰀵"
Windows = ""

# -----------------------
# USERNAME
# -----------------------
[username]
show_always = true
style_user = "bg:red fg:black"
style_root = "bg:red fg:bg"
format = '[ $user ]($style)'

# -----------------------
# DIRECTORY
# -----------------------
[directory]
style = "bg:magenta fg:bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# -----------------------
# GIT
# -----------------------
[git_branch]
symbol = ""
style = "fg:bg bg:yellow"
format = "[ $symbol $branch ]($style)"


[git_status]
style = "fg:bg bg:yellow"
format = "[($all_status$ahead_behind )]($style)"


# -----------------------
# LANGS
# -----------------------
[nodejs]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol $version ]($style)]'
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_extensions = ["js", "mjs", "cjs", "ts"]
detect_folders = ["node_modules"]

[c]
symbol = " "
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[rust]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[golang]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[php]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[java]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[kotlin]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[haskell]
symbol = ""
style = "bg:green fg:bg"
format = '[[ $symbol( $version) ]($style)]'

[python]
symbol = ""
style = "fg:bg bg:green"
format = "[ $symbol $version ($virtualenv) ]($style)"


# -----------------------
# CONDA
# -----------------------
[conda]
symbol = ""
style = "bg:cyan fg:bg"
format = '[$symbol $environment ]($style)'
ignore_base = false


# -----------------------
# CMD DURATION
# -----------------------
[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:bg"
disabled = false
show_notifications = true
min_time_to_notify = 45000

# -----------------------
# CHARACTER
# -----------------------
[character]
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_symbol = '[❮](bold fg:blue)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

# -----------------------
# YOUR CUSTOM PALETTE
# -----------------------
[palettes.void]
bg = "#FFFFFF"
fg = "#FFFFFF"

black = "#1A1A1A"
red   = "#F07178"
green = "#2A2A2A"
yellow = "#333333"
blue = "#282828"
magenta = "#252525"
cyan = "#2C2C2C"
white = "#3A3A3A"

bright_black = "#404040"
bright_red = "#FF8A95"
bright_green = "#454545"
bright_yellow = "#4A4A4A"
bright_blue = "#484848"
bright_magenta = "#464646"
bright_cyan = "#4C4C4C"
bright_white = "#505050"

cursor_text = "#C7CAC2"
cursor = "#3A3A3A"